apiVersion: v1
kind: Service
metadata:
  name: blacklight
  namespace: blacklight
spec:
  selector:
    app.kubernetes.io/name: blacklight
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
